apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worklenz-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: localhost   # or 127.0.0.1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: worklenz-frontend-service
            port:
              number: 5000
