apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: NodePort  # Change from LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080  # Choose a port between 30000-32767
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
  selector:
    app: traefik
