apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worklenz-db
spec:
  serviceName: "worklenz-db"
  replicas: 1
  selector:
    matchLabels:
      app: worklenz-db
  template:
    metadata:
      labels:
        app: worklenz-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: worklenz-secret
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: worklenz-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worklenz-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: worklenz-db-pvc
        - name: init-scripts
          configMap:
            name: worklenz-init-scripts
---

apiVersion: v1
kind: Service
metadata:
  name: worklenz-db
spec:
  selector:
    app: worklenz-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worklenz-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # db size
