apiVersion: v1
kind: Secret
metadata:
  name: worklenz-secret
type: Opaque
data:
  SESSION_SECRET: "WV9VUl9TRVNTSU9OX1NFQ1JFVF9IRVJF"  # Base64 of "YOUR_SESSION_SECRET_HERE"
  COOKIE_SECRET: "WV9DT09LSUVfU0VDUkVUX0hFUkU="      # Base64 of "YOUR_COOKIE_SECRET_HERE"
  DB_USER: "d29ya2xlbnpfYmFja2VuZA=="               # Base64 of "worklenz_backend"
  DB_PASSWORD: "c2VjdXJlcGFzc3dvcmQxMjM="           # Base64 of "securepassword123"
  DB_NAME: "d29ya2xlbnpfZGI="                       # Base64 of "worklenz_db"
  DB_HOST: "d29ya2xlbnotZGItMC53b3JrbGVuei1kYi5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs"  # Base64 of worklenz-db-0.worklenz-db.default.svc.cluster.local
  GOOGLE_CLIENT_ID: "MTIzNDUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20="  # Base64 of "12345.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA=="       # Base64 of "your-google-client-secret"
  JWT_SECRET: "WV9KV1RfU0VDUkVUX0hFUkU="             # Base64 of "YOUR_JWT_SECRET_HERE"
  AWS_ACCESS_KEY_ID: "QVdTX0FDQ0VTU19LRVlfSURfSEVS"  # Base64 of "AWS_ACCESS_KEY_ID_HERE"
  AWS_SECRET_ACCESS_KEY: "QVdTX1NFQ1JFVF9BQ0NFU1NfS0VZX0hFUkU="  # Base64 of "AWS_SECRET_ACCESS_KEY_HERE"
  S3_ACCESS_KEY_ID: "UzNfQUNDRVNTX0tFWV9JRF9IRVJF"  # Base64 of "S3_ACCESS_KEY_ID_HERE"
  S3_SECRET_ACCESS_KEY: "UzNfU0VDUkVUX0FDQ0VTU19LRVlfSEVS"  # Base64 of "S3_SECRET_ACCESS_KEY_HERE"

# use cmd  `echo -n 'worklenz_db' | base64` or powershell `[Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("worklenz_db"))`